services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    container_name: jenkins
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
    - "0"
    networks:
      - devops-network
      - mailhog-network

  app:
    image: leticialm/s107-project:latest
    container_name: app
    environment:
      - DATABASE_PATH=data/tarefas.json
    volumes:
      - ./data:/app/data
    networks:
      - devops-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mailhog-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tarefas
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
  mailhog-network:
    driver: bridge

volumes:
  jenkins_home:
  db_data: